### ISSUE TITLE
Make extension work without ext:dashboard

### ISSUE THREAD

**Issue by georgringer** [itx-informationssysteme/jobapplications#112]
This extension got a hidden dependency to ext:dashboard because it is required within `Services.yaml` but not enforced via e.g. `composer.json`.

See e.g. https://github.com/georgringer/doc/commit/5bebf78b396274d21a87123207c604e56013a17c and official documentation https://docs.typo3.org/c/typo3/cms-dashboard/main/en-us/Configuration/WidgetRegistration.html for examples

Please don't enforce loading ext:dashboard when not needed

**Comment by itx-benjamin-jasper** [comment]
Thanks, will do!
