### ISSUE TITLE
Could not find class definition for name "TYPO3\CMS\Extbase\Domain\Model\BackendUser". 

### ISSUE THREAD

**Issue by p-view** [itx-informationssysteme/jobapplications#116]
get error in list view when i connect contact with Be/User

 #1476045117 TYPO3\CMS\Extbase\Persistence\Generic\Exception\InvalidClassException
Could not find class definition for name "TYPO3\CMS\Extbase\Domain\Model\BackendUser". This could be caused by a mis-spelling of the class name in the class definition.

Tzpo3 12.4.5, jobapplications	3.0.0

**Comment by itx-benjamin-jasper** [comment]
Oh yeah, seems like we missed that they removed this class in v12... we'll have to roll our own.
I'll try to put a fix out asap
