### ISSUE TITLE
Problem with ExtensionManagementUtility::isLoaded('dashboard') in Service.php

### ISSUE THREAD

**Issue by ste101** [itx-informationssysteme/jobapplications#118]
![grafik](https://github.com/itx-informationssysteme/jobapplications/assets/359959/ddb6ca06-e67b-4753-81c2-0d861052ec82)
Version 3.0.1

**Comment by itx-benjamin-jasper** [comment]
Is this a composer installation? This seems like a loading order issue

**Comment by ste101** [comment]
Its a no-composer installation
