### ISSUE TITLE
Wrong upload path?

### ISSUE THREAD

**Issue by ste101** [itx-informationssysteme/jobapplications#119]
PDFs are uploaded to /typo3/typo3temp/var/typo3temp/jobapplications/
Seem not to be correct.

Version 3.0.1

**Comment by itx-benjamin-jasper** [comment]
Indeed that is not correct

**Comment by itx-benjamin-jasper** [comment]
Actually never mind, this path seems weird, because it's a non composer installation, you should probably make sure to secure this from public access if it isn't yet. The /typo3/typo3temp/var is the non-composer substitute for the private /var directory.
