### ISSUE TITLE
syntax error, unexpected ':', expecting ')' in /html/typo3/typo3conf/ext/jobapplications/Classes/Controller/ApplicationController.php line 722

### ISSUE THREAD

**Issue by p-view** [itx-informationssysteme/jobapplications#121]
after Update to 2.3.2 i got this Error, after then "Call to a member function isPackageActive() on null"
LIne 722: if ( $arguments["new_mail"] !== '' || ($arguments["timestamp"] != '' && (microtime(as_float: true) - (int)$arguments["timestamp"]) < $minMillisecondsToFillOutForm))

on typo3 11.5.30

only downgrade helps

**Comment by itx-benjamin-jasper** [comment]
Are you on PHP 7.4? The extension has a php version requirement of php 8 since 2.2.0

**Comment by p-view** [comment]
ok, thx. That helps. Thank you for the great Extension.
