### ISSUE TITLE
TYPO3 v12 compatibilty bug: the sys_language table is no more used

### ISSUE THREAD

**Issue by phil64** [itx-informationssysteme/jobapplications#125]
In TYPO3 v12, the sys_language table is no more present.

So, when generating "status elements", the function findLangUid crashes.
One need to use the SiteLanguage object to retrieve the language code.

See these changelogs:

- https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.3/Deprecation-94165-SysLanguageDatabaseTable.html
- https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96107-DeprecatedFunctionalityRemoved.html

**Comment by itx-benjamin-jasper** [comment]
Nice catch! Will fix as soon as I find the time.
