### ISSUE TITLE
Use of the Basic Metadata property og:url

### ISSUE THREAD

**Issue by zenoussi** [itx-informationssysteme/jobapplications#126]
Unfortunately, the url of the detail page is currently displayed, which leads to a 404 page:
`<meta property="og:url" content="https://karriere.example.site/postings/detail.html">`

Is it possible to output the url of the post?
`<meta property="og:url" content="https://karriere.example.site/postings/typo3-editor.html">`

Thanks a lot
Ulli

**Comment by itx-benjamin-jasper** [comment]
Hi, you are right the seo extension apparently does not handle this very well, you can however simply add the following viewhelper to your template override:

`<jobs:page.header.meta content="{f:uri.action(action: 'show', arguments: {posting : posting}, pageUid: settings.detailViewUid, controller: 'Posting', pluginName: 'DetailView', absolute: 1)}" name="og:url"/>`

I will add this to the default template as well.
