### ISSUE TITLE
Application Module returns error TYPO3Fluid\Fluid\View\Exception\InvalidSectionException

### ISSUE THREAD

**Issue by zenoussi** [itx-informationssysteme/jobapplications#128]
When I select the Application Module, I get the following error message:

_Core: Exception handler (WEB): Uncaught TYPO3 Exception: Section "content" does not exist. | TYPO3Fluid\Fluid\View\Exception\InvalidSectionException thrown in file /var/www/html/vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php in line 266. Requested URL: https://xxx.ddev.site/typo3/module/jobapplications?token=--AnonymizedToken--_

jobapplications 3.0.3
TYPO3 12.4.7
PHP 8.1.13

Greetings
Ulli

**Comment by itx-benjamin-jasper** [comment]
Did you include the static TypoScript?

**Comment by zenoussi** [comment]
yes, I included:
Jobapplications (jobapplications)
Jobapplications: [Optional] Include jQuery (if necessary) for working filters (jobapplications)

**Comment by itx-benjamin-jasper** [comment]
Okay, weird. Can you take a look into the "Active TypoScript" Setup Browser, to see if it looks anything like this?

<img width="689" alt="Bildschirmfoto 2023-11-27 um 08 19 46" src="https://github.com/itx-informationssysteme/jobapplications/assets/71708720/2b2bb775-cb21-4a60-af6d-3768bda1a3fc">

**Comment by zenoussi** [comment]
<img width="839" alt="Bildschirmfoto 2023-11-27 um 21 31 58" src="https://github.com/itx-informationssysteme/jobapplications/assets/4442136/1c289e62-4531-4ed3-9c7b-24bd9e3d2379">

**Comment by itx-benjamin-jasper** [comment]
Weird, this looks very normal. It seems that it tries to render the Frontend Layout, because that case content written in lowercase. Maybe you can do some debugging to see which template it tries to render and why

**Comment by zenoussi** [comment]
I have installed the extension again in another TYPO3 instance and the module works there.

The difference is that the current project is a multidomain instance: (1) kunde.de and (2) karriere.kunde.de

The extension or the static Typoscript is required in the root template of (2) karriere.kunde.de and is only integrated there - the module does not work this way.
If I add the static typoscript to the root template of (1) kunde.de, the module works.
If I then remove the static Typoscript in (2) karriere.kunde.de, the module also works.

Can you confirm the behaviour for a multidomain setup?

**Comment by benjasper** [comment]
This seems to be solved

**Comment by georgringer** [comment]
had the same issue on a site and not solved.

problem is that the module requires TS which is page based but the module doesn't have a page tree.

only solution IMO: use a ext_typoscript_setup.typoscript and load the minimal TS required. however it shouldn't be required at all and fallback to a proper template

**Comment by benjasper** [comment]
Fair point, I'll let go of the seperate folder for the backend layout... this is not useful at all. I'll push a fix in a moment. Let me know if this fixes the issue for you people.

**Comment by georgringer** [comment]
thanks, works fine
