### ISSUE TITLE
503-Error for "Show only postings of categories"

### ISSUE THREAD

**Issue by zenoussi** [itx-informationssysteme/jobapplications#131]
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: TYPO3\CMS\Extbase\Persistence\Generic\Query::logicalAnd(): Argument #1 must be of type TYPO3\CMS\Extbase\Persistence\Generic\Qom\ConstraintInterface, array given, called in /kunden/XXXXXX_XXXXX/xx-hosting/XXXXXXX/XXXXXXX/typo3cms/kunde-v12/releases/30/vendor/itx/jobapplications/Classes/Domain/Repository/LocationRepository.php on line 59 | TypeError thrown in file /kunden/XXXXXX_XXXXX/xx-hosting/XXXXXXX/XXXXXXX/typo3cms/kunde-v12/releases/30/vendor/typo3/cms-extbase/Classes/Persistence/Generic/Query.php in line 394. Requested URL: https://karriere.xxxxxx.com/arbeitswelten/spanabhebende-fertigung.html`

- TYPO3 v12.4.8
- PHP 8.1.24
- jobapplications 3.0.3

**Comment by itx-benjamin-jasper** [comment]
Thanks, this was indeed broken
