### ISSUE TITLE
Page links are not resolved to URL in TYPO3 12

### ISSUE THREAD

**Issue by firmenpunkt** [itx-informationssysteme/jobapplications#139]
This has been reported before, and it it may be the case that it has been resolved in TYPO3 11, but in TYPO3 12 the problem is there, the links are not resolved on the frontend.  
3.0.4 TER installation

**Comment by lstitx** [comment]
Hi Firmenpunkt,
So far, I haven't been able to reproduce the issue. Could you please specify which field the links are not being resolved for?
Thank you!

**Comment by benjasper** [comment]
Could not reproduce, please reopen if still an issue
