### ISSUE TITLE
Indexing API with slugs

### ISSUE THREAD

**Issue by bm1-phillip** [itx-informationssysteme/jobapplications#141]
Hello,

we are experiencing problems when using the Indexing API with slugs.

The links are pushed without slugs, which is why I sometimes find indexed pages without slugs in the Google Search Console.

The problem is that these pages lead to a 404 error and the job is not displayed.

The simplest option would be to push the important link with slugs. 

Perhaps we have just corrected something incorrectly. Unfortunately we are using an older version.

TYPO3 10.4
Version 1.03

**Comment by benjasper** [comment]
Hi Phillip, we are stepping away in the newest version of the extension from the indexing api, as maintaing it is too work intensive while the benefits are neglectable. We would rather recommend to use a sitemap instead, which should be sufficient. 

See the example here: https://docs.typo3.org/p/itx/jobapplications/main/en-us/Installation/Index.html#sitemap-example
