### ISSUE TITLE
Missing attached files in notification mail

### ISSUE THREAD

**Issue by r4fx** [itx-informationssysteme/jobapplications#142]
I have the following setup:

`Should Applications be saved in the backend` is set to false
`emailPrivacyMode` is set to false

How in such scenario receive in the notification email files attached by the applicant?

**Comment by lstitx** [comment]
Hi,
With your current setup, this won't be possible. You are neither sending any information via email (which you have selected with the emailPrivacyMode setting) nor persisting the data.

**Comment by r4fx** [comment]
How then the setup should be?

**Comment by lstitx** [comment]
You need to set one of your settings to true.

**Comment by lstitx** [comment]
This wasn't identified as an issue/bug and can be fixed by changing the settings.
