### ISSUE TITLE
DB-Analyzer can't handle SQL statement

### ISSUE THREAD

**Issue by akohlheyer** [itx-informationssysteme/jobapplications#145]
Is it possible to change    
```
message                   text         DEFAULT '' NOT NULL,
``` 
to
```
message                   text,
```

in [this line](https://github.com/itx-informationssysteme/jobapplications/blob/main/ext_tables.sql#L116), if this wasn't on purpose?

**Comment by zenoussi** [comment]
ALTER TABLE `tx_jobapplications_domain_model_application` CHANGE `message` `message` TEXT NOT NULL
Current value: message TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`

@akohlheyer hope so too

**Comment by lstitx** [comment]
Hi, what's the issue exactly?

**Comment by akohlheyer** [comment]
> Hi, what's the issue exactly?

as far as my requirement is concerned, I try to use the "Analyze Database Structure" function in the Install tool. The mentioned field won't disappear after exexuting the suggested actions. Changing the mentioned line above fixes this misbehaviour.
