### ISSUE TITLE
Contact Details not selectable and not showing

### ISSUE THREAD

**Issue by Inovanet** [itx-informationssysteme/jobapplications#146]
When selecting to show contacts, no entries are displayed though they exist on the selected page.
Single contacts are not selectable.

TYPO3 Version: 11.5.32
Plugin: 2.3.3

**Comment by lstitx** [comment]
Hi Inovanet, have you selected the appropriate Record Storage Page?

**Comment by Inovanet** [comment]
The appropriate Record Storage Page is selected but no data is displayed.
Also there are some bugs when implementing the plugin like missing paranthesis.

**Comment by lstitx** [comment]
I tried replicating the issue with TYPO3 v11.5.32 and Plugin v2.3.3 and was not able to do so. Please try the following steps to solve your issue: 

1. Switch to the list module and create a contact on your storage Page. Make sure to select the language/s you want your contact to show up for. 
2. Add the Plugin 'Jobapplications: Contact Display' to your Contacts Page. Select the contacts you want to display + the Record Storage page where you just created your contact. Make sure the contact Language + Contacts Page Language match. 
3. View your Webpage in the frontend. 

What do you mean by 'there are some bugs when implementing the plugin like missing paranthesis'?

**Comment by Inovanet** [comment]
'Jobapplications: Contact Display' doesn't give me an option to select the contacts I want to display.

The bug looks like this:
![Error](https://github.com/itx-informationssysteme/jobapplications/assets/25638983/3fb9c922-f6bb-4832-b1ef-669a511d1832)

**Comment by lstitx** [comment]
Have you installed the plugin via composer? The plugin needs at least php 8.0 to work.

**Comment by Inovanet** [comment]
The extension was installed via extension manager / extension repository.
When using v2.1.0 the problem is still present. 
I can only select the page where the contacts are located but not which contacts should be shown.

**Comment by lstitx** [comment]
Which php version are you using?

**Comment by Inovanet** [comment]
Currently php 7.4

**Comment by lstitx** [comment]
Please consider updating your PHP version. As mentioned previously:

> Have you installed the plugin via composer? The plugin needs at least php 8.0 to work.

**Comment by Inovanet** [comment]
Updated to PHP 8.0.30 and jobapplications 2.3.3
Still the same result, no contacts are selectable
PHP Warning: Undefined array key "selectedContacts" in /typo3conf/ext/jobapplications/Classes/Controller/ContactController.php line 67

**Comment by lstitx** [comment]
The entire flexform settings seems to be missing. Please make sure the contactdisplay.xml exists in jobapplication/Configuration/FlexForms and it is correctly registered in the tt_content. Here's the code that's used in the extension, that might be different for you: https://github.com/itx-informationssysteme/jobapplications/blob/main/Configuration/TCA/Overrides/tt_content.php 

![image](https://github.com/itx-informationssysteme/jobapplications/assets/126770572/e1926acd-c9f6-4e77-bdf5-095c6bc60965)

Clear Caches and analyze the database structure. Is there an error in your logs that could help me further? Have you had any problems with plugin conflicts in the past?

**Comment by Inovanet** [comment]
The contactdisplay.xml exists in jobapplication/Configuration/FlexForms and is registered in tt_content like you did in https://github.com/itx-informationssysteme/jobapplications/blob/main/Configuration/TCA/Overrides/tt_content.php.

Caches are cleared, autoload got dumped. The only error is PHP Warning: Undefined array key "selectedContacts" in /typo3conf/ext/jobapplications/Classes/Controller/ContactController.php line 67
Log is filled with this error and no problems with plugin conflicts are known.

Still get the same layout and can't select the contacts.

**Comment by lstitx** [comment]
I'm really sorry, but I can't reproduce the error. The last idea I can offer is to uninstall and reinstall the extension now that the PHP version has been updated.

**Comment by Inovanet** [comment]
Even this approach did not fix it.

**Comment by lstitx** [comment]
Unfortunately, we are unable to reproduce or recreate the problem. It is therefore likely that the problem is not with the extension. I would suggest setting up a completely new TYPO3 installation without any dependencies as a test to see exactly where the problem lies.
