### ISSUE TITLE
Unable to render image tag in List and Detail View

### ISSUE THREAD

**Issue by sruhani** [itx-informationssysteme/jobapplications#151]
The error message does not provide a clear indication of the exact cause of the issue. The problem occurs when I use my provider extension in combination with the Mask extension.

**Important Notes:**
- The same configuration worked without issues under TYPO3 10 and 11.
- I have already optimized my extension with TYPO3 Rector for TYPO3 12.
- Interestingly, the setup works when I use the Bootstrap Package instead, which suggests that the basic configuration itself is functioning properly.

**Steps to Reproduce:**
1. Install TYPO3 12.
2. Use my customized provider extension in combination with the Mask extension.
3. Create a page with an image stored in the `fileadmin` directory.
4. The error occurs when rendering the image.

**Expected Behavior:**
The image should render without errors in the frontend.

**Additional Information:**
- TYPO3 Version: 12
- PHP Version: 8.2
- Extensions: Custom provider package in combination with Mask

Has anyone experienced a similar issue or has any ideas on how this problem can be resolved?

Thank you in advance for your support!

**Comment by benjasper** [comment]
Hi, can you provide the exact error message?

**Comment by benjasper** [comment]
Seems weird, that this error is happening, but maybe try it like this: 
`<f:image class="img-fluid" image="{posting.listViewImage}"/>`

**Comment by the-andyman** [comment]
Many thanks for the quick reply. That seems to work.
