### ISSUE TITLE
Error when deleting application with attached files

### ISSUE THREAD

**Issue by ste101** [itx-informationssysteme/jobapplications#152]
When deleting an application with attached files within the backend module I'm getting an error
`No file reference (sys_file_reference) was found for given UID: "397"`

The files and the folder are deleted.

**Comment by benjasper** [comment]
I can't reproduce the issue, do you have a strack trace?

**Comment by paeddym** [comment]
Hi, the issue stems from line 263 in BackendController.php
If you add `return` at the start of the line the error shouldn't appear anymore
