### ISSUE TITLE
Invalid identifier  

### ISSUE THREAD

**Issue by slowhand11** [itx-informationssysteme/jobapplications#157]
At fileupload we get "Invalid identifier in /homepages/xxx/xxxxxxxxx/htdocs/typo3_2021/typo3conf/ext/jobapplications/Classes/Utility/UploadFileUtility.php line 97"

Strange has that nothing is changed in filesystem, hosting or anything else.

T3 10.4
jobapplications Vers. 1.0.5

**Comment by benjasper** [comment]
That does seem weird, this seem to stem from here: https://github.com/itx-informationssysteme/jobapplications/blob/679d34183120e3de16db3f9b4117a92b63542ee3/Classes/Utility/UploadFileUtility.php#L95 but no idea, what the actual input is. Maybe you can log the identifier there to see, why it would be misshaped.

**Comment by slowhand11** [comment]
Hi, Ive logged both:
$uniqueIdentifier = '/tmp/phpBnwBPZ'
$filePath = ''/kunden/homepages/13/d50721332/htdocs/typo3_2021/typo3temp/var/typo3temp/job
   applications//tmp/phpCdvGtT/'
   
Both is looking weird.

**Comment by benjasper** [comment]
Okay, this seem not right, as this should be a file id generated by file pond. I'm afraid you have to do some debugging by yourself, to find out where the php temp path is coming from.

**Comment by slowhand11** [comment]
Was an issue with filepond config
