### ISSUE TITLE
Typo 13.4 finde keine records

### ISSUE THREAD

**Issue by TobiXT** [itx-informationssysteme/jobapplications#163]
Hallo,
Ich habe die Extension in Typo3 13.4.1 installiert und ich kann keine records einstellen.
Ich hab es auch im Typoscript eingestellt und alle Cashe´s gelöscht.
![comp](https://github.com/user-attachments/assets/3dd0df24-14bc-4e9f-90fb-ab3fee1e6cea)
![Typo](https://github.com/user-attachments/assets/7f06bd1d-0d90-484c-89b2-6a7143aa70e0)
![record](https://github.com/user-attachments/assets/952df7a9-5556-4ff9-974f-ced257227141)

**Comment by benjasper** [comment]
Könnte es sich dabei um ein Rechte Thema handeln? Die Liste der verfügbaren Records sieht mir sehr leer aus.

**Comment by TobiXT** [comment]
Eigentlich nicht ich bin sowohl System Maintainer als auch Admin. Momentan sind nicht viele Extensions installiert außer tt_address und news.

**Comment by benjasper** [comment]
Verstehe, aber irgendwas wird da schon eingeschränkt sein, denn da fehlen ja auch die System Records, Kategorien etc.

Ich fürchte ich kann da nicht viel helfen, denn bei mir und bei anderen funktioniert das einwandfrei. Ich denke es hat irgendwas mit der TYPO3 Umgebung zu tun.

**Comment by firmenpunkt** [comment]
Same here. Ich kann nur News hinzufügen im List modul. Was macht Georg Ringer anders? :)

**Comment by firmenpunkt** [comment]
Ich habe deine Einschränkung gefunden, Bei mir war es auch der Fall. 
Bei der Page TSConfig ist sicherlich sowas eingestellt: 
![grafik](https://github.com/user-attachments/assets/9d2e2ca8-c714-412f-9943-84967923b1d6)


(THX Manuel Munz)

**Comment by benjasper** [comment]
Nice!
