### ISSUE TITLE
selectize.css is no css

### ISSUE THREAD

**Issue by der-phillip** [itx-informationssysteme/jobapplications#17]
In this file on commit #228a710 is html and not css.
[/Resources/Public/Css/selectize.css](https://github.com/itx-informationssysteme/jobapplications/commit/228a710a901b7713475833ab99a3ba93a0faadac#diff-ffff712858b42ee2f2dd7b8cf326720c6745b620ced6e5fff2da3d753d3244ae)

**Comment by itx-benjamin-jasper** [comment]
Interesting, we will investigate this.

**Comment by itx-benjamin-jasper** [comment]
Fixed in develop
