### ISSUE TITLE
Filtering exception 

### ISSUE THREAD

**Issue by der-phillip** [itx-informationssysteme/jobapplications#18]
As soon as I filter for something, I get the following message.

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476107295: PHP Warning: Use of undefined constant is_array - assumed 'is_array' (this will throw an Error in a future version of PHP) in /typo3conf/ext/jobapplications/Classes/Domain/Repository/PostingRepository.php line 255

**Comment by der-phillip** [comment]
I set the exceptionalErrors to live. Now the general warning is no longer displayed.

The filters now work except for the employmentType

> Unsupported or non-existing property name "employmentType" used in relation matching.

**Comment by itx-benjamin-jasper** [comment]
Thanks, regarding the warning, there is a small typo in the code. The other error should not happen. Will investigate.

**Comment by itx-benjamin-jasper** [comment]
The warning issue should be fixed now, is the filter issue still there?
