### ISSUE TITLE
Upload error 

### ISSUE THREAD

**Issue by febuc** [itx-informationssysteme/jobapplications#19]
As soon as I try to upload an application I get this error message:

(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Illegal string offset 'error' in /var/www/clients/client13/web228/web/typo3conf/ext/jobapplications/Classes/Controller/ApplicationController.php line 336

**Comment by itx-benjamin-jasper** [comment]
Could you specify which upload fields you were using, as well as how much files you uploaded for each field(in case you are using the four fields setting).
Also what PHP and TYPO3 version are you using?

**Comment by febuc** [comment]
When the error occured I was using only the mandatory fields: Lebenslauf and Anschreiben. In each of them I only had one file, which was the same. 
My PHP version was 7.4.11 and Typo3 10.4.9

**Comment by itx-benjamin-jasper** [comment]
I think I've found the problem, do you have a composer installation and if so would you be able to switch the extensions version to the develop branch (itx/jobapplications: "dev-develop") to verify the fix works?

**Comment by febuc** [comment]
Since I'm not able to check your changes (because I downgraded to 0.9.12 in order to make it work) you can close this issue if you are fine with it.

**Comment by itx-benjamin-jasper** [comment]
Ok, no problem, it should be fixed in the latest release though.
