### ISSUE TITLE
Add new Deployment-Type

### ISSUE THREAD

**Issue by chschatz** [itx-informationssysteme/jobapplications#24]
How can I add a new deployment-type for selecting in the filter?
I want to add a deployment-type without losing ability to update the extension.

**Comment by itx-benjamin-jasper** [comment]
This might have become irrelevant now(sorry about that), but for completions sake:

- The field employment_type is based on the google employment types so it isn't really designed to be modified
- If you want to have your own I would suggest to create a new field and use that
