### ISSUE TITLE
Multiselect is not possible in jobapplications	0.9.12

### ISSUE THREAD

**Issue by ravishanankar** [itx-informationssysteme/jobapplications#26]
Multiselect is not possible in jobapplications	0.9.12 when we add the multiselect option for careerLevel and Location its gives error 

(1/1) TYPO3\CMS\Extbase\Mvc\Exception\InvalidArgumentValueException
Input not valid.
![image-6](https://user-images.githubusercontent.com/8793864/106233469-9f879000-621c-11eb-8a45-7e0db55246f6.png)

Please help me regarding this if any solution for this ?

**Comment by itx-benjamin-jasper** [comment]
Yes that's right its not supported on this version. On the newer versions it should work though.
