### ISSUE TITLE
Field address_post_code not suitable for Germany

### ISSUE THREAD

**Issue by peerlight** [itx-informationssysteme/jobapplications#32]
Hi,

TCA of address_post_code in tx_jobapplications_domain_model_location has
```
'size' => 4,
'eval' => 'int'
```
In Germany we need 5 digits and the possibility of a leading zero

This would also mean to adapt .sql int(11) to varchar(20) like in tt_address

Please check same field in tx_jobapplications_domain_model_application too

**Comment by itx-benjamin-jasper** [comment]
Yes this is indeed a bug, this should be definitely a string.

**Comment by peerlight** [comment]
Should not "address_post_code" in 'tx_jobapplications_domain_model_application' also be changed?
