### ISSUE TITLE
TYPO3 Error by using local Partials and Templates

### ISSUE THREAD

**Issue by Fotopoly** [itx-informationssysteme/jobapplications#33]
If i connect a local template - Templates > Posting > List.html i get the following error if i use the filter:
**Return value of ITX\Jobapplications\Domain\Model\Constraint::getCareerLevel() must be of the type array, null returned**

How can i fix this issue in TYPO3 9.5.x and jobapplication 1.0.1? 

Best regards!

**Comment by Fotopoly** [comment]
There are many errors if i use the filter, if the partials local stored.

Return value of ITX\Jobapplications\Domain\Model\Constraint::getDivision() must be of the type array, null returned

**Comment by itx-benjamin-jasper** [comment]
Sorry I can't seem understand whats going on here, can you elaborate on what you did and whats going wrong?
