### ISSUE TITLE
Error for non admin users in dashboard with TYPO3 10.4 

### ISSUE THREAD

**Issue by peerlight** [itx-informationssysteme/jobapplications#34]
After activating dasboard widgets the user gets this error when opening the dashboard:

`Call to undefined method TYPO3\CMS\Dashboard\Widgets\Provider\ButtonProvider::initializeView() | Error thrown in file .../typo3conf/ext/jobapplications/Classes/Widgets/Provider/BackendModuleButtonProvider.php in line 48.`

Is `check('modules', 'web_jobapplications_backend')` correct or should it be `web_JobapplicationsBackend`?

No problem for admin users

**Comment by itx-benjamin-jasper** [comment]
You are absolutely right, thanks!
