### ISSUE TITLE
SEO: Jobs Sitemap

### ISSUE THREAD

**Issue by ulme** [itx-informationssysteme/jobapplications#35]
Hi,

I tried to insert the job positions into a seo sitemap with the following code (based on creation of news sitemap):

plugin.tx_seo.config {
  xmlSitemap {
    sitemaps {
      jobs {
        provider = TYPO3\CMS\Seo\XmlSitemap\RecordsXmlSitemapDataProvider
        config {
          table = tx_jobapplications_domain_model_posting
          sortField = uid
          ### Die ID der Ordners in dem die News liegen ###
          pid = the pid
          ### Die ID der Ordners in dem die News liegen ###

          recursive = 2
          url {

            ### Die ID der Detailseite angeben ###
            pageId = the pid
            ### Die ID der Detailseite angeben ###

            fieldToParameterMap {
              uid = tx_jobapplications_detailview[posting]
            }
            additionalGetParameters {
              tx_jobapplications.controller = Posting
              tx_jobapplications.action = show
            }
            useCacheHash = 1
          }
        }
      }
    }
  }
}
Generally it worked but the urls in die sitemap are not "enhanced". What can be done?

Best Regards

**Comment by itx-benjamin-jasper** [comment]
Hi, I can't confirm that this works but you might be missing the slug for the enhanced urls. So slug instead of uid maybe?

**Comment by ste101** [comment]
'additionalGetParameters' are wrong.

```
            jobs {
                provider = TYPO3\CMS\Seo\XmlSitemap\RecordsXmlSitemapDataProvider
                config {
                   table = tx_jobapplications_domain_model_posting
                   sortField = uid
                   lastModifiedField = tstamp
                   pid = 551
                   recursive = 0
                   url {
                      pageId = 548
                      fieldToParameterMap {
                         uid = tx_jobapplications_detailview[posting]
                      }
                      additionalGetParameters {
                         tx_jobapplications_detailview.controller = Posting
                         tx_jobapplications_detailview.action = show
                      }
                   }
                }
            }
```
