### ISSUE TITLE
Log entry is not inserted

### ISSUE THREAD

**Issue by ashupatel1990** [itx-informationssysteme/jobapplications#37]
Hi,
$this->logger->info('[ITX\\Jobapplications\\Task\\CleanUpApplications]: '.$resultCount.' Applications deleted.');

This does not write log into "sys_log"

Can you tell me when this log writes in DB and which table?

Thanks!

**Comment by itx-benjamin-jasper** [comment]
It should be logged to a file: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Logging/Quickstart/Index.html#set-logging-output
