### ISSUE TITLE
No possibilty to choose a different file storage than 'fileadmin' to store applications

### ISSUE THREAD

**Issue by febuc** [itx-informationssysteme/jobapplications#38]
First of all, I would like to say that this job extension is really great and can be edited in many ways.
But not in the way I want to do it at the moment, at least I don't see a way.

I would like to have the applications stored in a different file storage than fileadmin (e.g. a secured file storage), but can't change the storage path.

**Comment by itx-benjamin-jasper** [comment]
Thank you! That would be indeed a feature worth implementing. It is not configurable yet, but unitl then the file storage mount is hardcoded inside of ApplicationController and the handleFileUpload[Multiple]().
