### ISSUE TITLE
Add to sitemap with parameter 'postingApp'

### ISSUE THREAD

**Issue by ste101** [itx-informationssysteme/jobapplications#41]
I can add the job to the sitemap.xml but only without the parameter 'postingApp'.
The problem is that the value of uid is needed two times.

Is there a way to add the parameter sitemap configuration?

**Comment by ste101** [comment]
I made a quick patch to get rid of the paramter 'postingApp'.
ApplicationController.php:
```
201c201
< 			if ($posting === null && $_REQUEST['postingApp'])
---
> 			if ($posting === null)
203c203,204
< 				$postingUid = (int)$_REQUEST['postingApp'];
---
> 				$arguments = \TYPO3\CMS\Core\Utility\GeneralUtility::_GET("tx_jobapplications_detailview");
> 				$postingUid = (int)$arguments['posting'];
```
As you wrote in 'newAction' there should be a better way.
I think it could be done a bit more elegant.
Are there any drawback with this solution?

**Comment by itx-benjamin-jasper** [comment]
I like this solution, does it work with route enhancers as well? If so, feel free to create a PR against the dev branch.
