### ISSUE TITLE
hide pagination - show job title in detail page?

### ISSUE THREAD

**Issue by pixelbreit** [itx-informationssysteme/jobapplications#42]
Thanks for the great extension. 
I have the following two questions:

1. Is there a way to optionally hide the pagination?
If not, this would be a useful feature.

2. Is it possible to display the job title as a title tag in the detail page?
Preferably I would like to read it out via typoscript.
I tried the following, but unfortunately it doesn't work:

```
temp.jobsBrowsertitle = COA
temp.jobsBrowsertitle { 
  10 = RECORDS
  10 {
    source = {GPvar:tx_jobapplications|uid}
    source.intval = 1
    source.insertData = 1
    tables = tx_jobapplications_domain_model_posting 
    conf.tx_jobapplications_domain_model_posting > 
    conf.tx_jobapplications_domain_model_posting = TEXT
    conf.tx_jobapplications_domain_model_posting {
      field = title
      htmlSpecialChars = 1
    }
    conf.tx_jobapplications_domain_model_posting.field = title
  }
  20=TEXT
  20.data = DB:sys_template:1:sitetitle
  20.wrap = &nbsp;&#124;&nbsp;|
}
page.headerData.10 > 
page.headerData.10 = COA 
page.headerData.10 < temp.jobsBrowsertitle 
page.headerData.10.wrap = <title>|</title> 
```
Line 5 (with GPvar) is probably not correct

**Comment by itx-benjamin-jasper** [comment]
1. Yes, you can just throw it out of the template.
2. Yes this should be the standard behaviour: There is a PageTitleProvider that sets the title for detail pages, maybe you have to change the priority of it here? (https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/PageTitleApi/Index.html#define-priority-of-pagetitleproviders). Also there is a setting in the plugin itself, where you can use templating to customize the name (https://docs.typo3.org/p/itx/jobapplications/1.0/en-us/User/Index.html#define-page-title).

**Comment by pixelbreit** [comment]
Many thanks for the answers!

1. Yes, you can remove that in the template, but then the navigation is generally no longer displayed. 
In my case, the most recent 5 jobs should be displayed on the start page, and below that a button to the other or all job offers on another page.
No navigation would be needed on the start page, but it would be needed on the page with all the job offers. 
In my opinion, a selection option in the backend of the plugin as to whether the page navigation is displayed would be a useful feature. 
 
2. That helped me a lot!
 
3. And one more question: 
Is there a route enhancer for the success page? 
There is already one for the detail and form view. 
At the moment, an ugly URL with parameters is displayed after submitting the form. 
Here is an example (wrapped for better readability)
```
https://www.mydomain.com/
?tx_jobapplications_successpage[action]=success
&tx_jobapplications_successpage[controller]=Application
&tx_jobapplications_successpage[firstName]=Firstname
&tx_jobapplications_successpage[lastName]=Lastname
&tx_jobapplications_successpage[postingUid]=2
&tx_jobapplications_successpage[problems][problemWithApplicantMail]=0
&tx_jobapplications_successpage[problems][problemWithNotificationMail]=0
&tx_jobapplications_successpage[problems][savedInBackend]=1
&tx_jobapplications_successpage[salutation]=mr
&cHash=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Comment by itx-benjamin-jasper** [comment]
1. I see, you might want to customize this on a per project basis yourself or split it into two different templates.
2. Great to hear!
3. There is not because it doesn't really make sense for me, because the data would still be there but more clearly to read. Also this page is not SEO relevant. You can create a route enhancer yourself though. If you do, feel free to share it!
