### ISSUE TITLE
Loading of selectize in List.html

### ISSUE THREAD

**Issue by peerlight** [itx-informationssysteme/jobapplications#45]
JS throws error if jQuery is loaded to the body (after selectize)

workaround: use TS 

consider asset collector for future versions (when support for TYPO3 v9 is skipped)

**Comment by itx-benjamin-jasper** [comment]
Why would you include jQuery in the body? Are you talking about your jQuery version or the one that comes with the extension?

**Comment by peerlight** [comment]
This jQuery comes from the sitepackage (other extension) and is loaded with concat/compress the usual way to the end of the body

**Comment by itx-benjamin-jasper** [comment]
Seems like an issue that people can easily solve themselves. But you are right we will definitely use the asset collector once v9 is dropped.
