### ISSUE TITLE
Are there any plans for TYPO3 11LTS?

### ISSUE THREAD

**Issue by peerlight** [itx-informationssysteme/jobapplications#53]
Do you have any plans to make jobapplications compatible with TYPO3 11LTS?

**Comment by itx-benjamin-jasper** [comment]
Yes absoluteley, we plan on doing that early next year. There is a branch already you can follow: "update-v11". Although there is not much progress yet.

**Comment by peerlight** [comment]
I will give the update-v11 branch a try in the near future.

What is still missing and is there a release already scheduled?

**Comment by itx-stefanie-doell** [comment]
we have only two more things to do: additional testing and feature #21 - allow multiple store locations. this will be a breaking change, so we want to do it before the release. 
We hope we can make the official release in the next 4 weeks, but we can't make any promises. 
Let us know if you have any problems with the update-v11 branch (or if everything is fine - this would add to our testing)

**Comment by itx-stefanie-doell** [comment]
right now we think that all bugs in the update-v11 branch are solved and the only open issue is the multiple location feature request (nearly done, only the upgrade wizard is missing right now)

**Comment by itx-stefanie-doell** [comment]
we finally did it! :)
Please make sure to read the changelog carefully, compare overriden templates and to run the upgrade wizard because there are breaking changes.
