### ISSUE TITLE
Typo in JobsApplicantMail.html

### ISSUE THREAD

**Issue by rcheetah** [itx-informationssysteme/jobapplications#57]
In the file `Resources/Private/Templates/Mail/JobsApplicantMail.html ` there are typos on line 30 and 31.

The Replacement-Keys `%applicantLastName%` and `%applicantFirstName%` are falsely camelized. They word 'name' should not be capitalized. Therefore, replacement in Mails doesn't work. 

The correct names are **`%applicantLastname%`** and **`%applicantFirstname%`**

**Comment by itx-stefanie-doell** [comment]
Hi! 
Thank you for reporting that bug. We will fix this issue in the next two weeks.

**Comment by itx-stefanie-doell** [comment]
Aligned with coding conventions I decided to use the keys **%applicantLastName%** and **%applicantFirstName%** further on. You can use the correct names in the templates with any worry about future updates. In the next update I will fix the description at the plugin.
