### ISSUE TITLE
Fluid error in backend module

### ISSUE THREAD

**Issue by peerlight** [itx-informationssysteme/jobapplications#63]
Opening the backend module under WEB > leads to the following error:

```
(1/1) #1257246929 TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException
Tried resolving a template file for controller action "Backend->listApplications" in format ".html", but none of the paths contained the expected template file (Backend/ListApplications.html). The following paths were checked: .../typo3conf/ext/jobapplications/Resources/Private/Templates/
```
If this is true, the files are looked up in the wrong place:

looking for `jobapplications/Resources/Private/Templates/Backend/ListApplications.html`

which seems to be in  `jobapplications/Resources/Private/Backend/Templates/Backend/ListApplications.html `

PHP 7.4.x
TYPO3 11.5.10
jobapplications 2.0.0

**Comment by itx-benjamin-jasper** [comment]
Can't reproduce

**Comment by vbryan** [comment]
@peerlight hi. do you find way to resolve that issue?
