### ISSUE TITLE
Return value of ITX\Jobapplications\Controller\ApplicationController::handleFileUpload() must be an instance of ITX\Jobapplications\Controller\mixed, instance of TYPO3\CMS\Core\Resource\File returned

### ISSUE THREAD

**Issue by peerlight** [itx-informationssysteme/jobapplications#66]
This 503 occurs after submitting application form in frontend

Nevertheless, files are already uploaded and application is saved in backend. But mail is not being send.

Error is on application page with this URL, not on thank you page
`https://SITE/stellenangebote/bewerben?tx_jobapplications_applicationform%5Baction%5D=create&tx_jobapplications_applicationform%5Bcontroller%5D=Application&tx_jobapplications_applicationform%5Bposting%5D=27&cHash=647411e79e499bb427f81634ccd1d1b4`

PHP 7.4
TYPO3 11.5.10
jobapplications 2.0.0

**Comment by peerlight** [comment]
return type "mixed" is available from PHP 8.0 onwards; not in PHP 7.4

**Comment by zenoussi** [comment]
Thank you for this great extension!
Unfortunately I can't upgrade to PHP 8 but I would love to use the extension.
Can you predict when this bug will be fixed?

**Comment by itx-stefanie-doell** [comment]
Hi,
we are very busy right now and to look and this issue more deeply we would need to downgrade our local development environment to php 7.4. The "bug" is probably only the incompatibility with the "mixed" return value, but of course we can't make a release without proper testing. Therefore it will take some time.
Did you have a look in the function "handleFileUpload"? Please try to remove ": mixed"
![image](https://user-images.githubusercontent.com/95851897/173007441-47f8751e-10c9-49ba-ba17-f7076d9bea2c.png)
and then test again. Thank you

**Comment by slowhand11** [comment]
removing ": mixed" works!
