### ISSUE TITLE
Error: The ViewHelper "<jobs:condition.inArray>" could not be resolved

### ISSUE THREAD

**Issue by zenoussi** [itx-informationssysteme/jobapplications#71]
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1407060572: Fluid parse error in template Posting_action_list_472b805d74e6039a9c0b513aed317b9f89b2a5b8, line 28 at character 1. Error: The ViewHelper "<jobs:condition.inArray>" could not be resolved. Based on your spelling, the system would load the class "ITX\Jobapplications\ViewHelpers\Condition\InArrayViewHelper", however this class does not exist. (error code 1407060572). Template source chunk: <f:form.select.option additionalAttributes="{jobs:condition.inArray(needle: division, haystack: constraint.division, then: '{selected: true}')}" value="{division}"> | TYPO3Fluid\Fluid\Core\Parser\Exception thrown in file /html/XXXXXX/vendor/typo3fluid/fluid/src/Core/Parser/TemplateParser.php in line 161. Requested URL: https://XXXXXX.XXXXXX.de/karriere/list.html

Server: Mittwald
PHP: 7.4-latest FPM (7.4.29) and 8.0-latest FPM (8.0.19)
TYPO3 v11.5.10
jobapplications v2.0.0

**Comment by itx-stefanie-doell** [comment]
the solution is in the dev Branch right now and will be part of the next deployment
