### ISSUE TITLE
Errror by uploading files in Application Form

### ISSUE THREAD

**Issue by creationell** [itx-informationssysteme/jobapplications#79]
If you want to upload a file (pdf, 11KB) in the application form you get an error. The extension was not overwritten, the default values of the extension are used. TYPO3 11 is the version and the PHP version is 7.4. I have also tested it on version PHP 8.0, same error.****
PHP: max_upload_size = 100MB

**Comment by jensmarquardt** [comment]
Push.

I have the same problem. Is there any update?

@creationell 
Did you solve the problem?

**Comment by itx-benjamin-jasper** [comment]
Hi there,

were you upgrading from an older system or do you have this issue in a new TYPO3 v11 Installation? We couldn't reproduce the issue before, and still can't.

The only thing I can tell you, that you might want to check if your [eID-Configurations](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/9.4/Deprecation-85646-DeprecateEIDImplementedAsScript.html) are correct as this extension is using it and it seems it can't find the eID Route.

You can check it by going into the Configuration Backend Module and check there whether the eID-Middleware exists and is one of the first few entries. Also you might want to check whether the eID registration actually made it into your system, like so:

![screen_configuration_eid](https://user-images.githubusercontent.com/71708720/211518763-cfd1cd0c-d44f-4056-b69d-6e1970f2064b.jpeg)

**Comment by itx-benjamin-jasper** [comment]
No response
