### ISSUE TITLE
Error on submitting Jobapplication form.

### ISSUE THREAD

**Issue by tonytony60** [itx-informationssysteme/jobapplications#85]
we used typo3 9.5 and Jobapplication version 1.0.7

After filup jobapplication form and submit it. we will get error like below.

	
```
#Oops, an error occurred!
PHP Warning: array_splice() expects parameter 2 to be int, string given in htdocs/public/typo3conf/ext/jobapplications/Classes/Controller/ApplicationController.php line 329
```

can you please help me out on this.

Thanks

**Comment by itx-stefanie-doell** [comment]
Hi,
the problem sounds like there are upload files missing.
DO you use the single or the multi upload?
Which php version do you have in use?

**Comment by tonytony60** [comment]
Thanks. Yes you're right. There's missing upload files.
