### ISSUE TITLE
Selected filter option lost when using pagination

### ISSUE THREAD

**Issue by KamalNayanParmar** [itx-informationssysteme/jobapplications#90]
I am facing issue with pagination after search.
I have TYPO3 11.5 and php 8 configuration, i installed `jobapplication` extension and when i am searching job with location the pagination  is working,

![image](https://user-images.githubusercontent.com/103017407/233046332-f20ff185-f2f3-485b-9329-c02344a2ff15.png)

When I click on next page or goes into another page of filtered list of job, it will removed filter's option and show all pagination with respective pagination.  

![image](https://user-images.githubusercontent.com/103017407/233046921-2547bf30-fc57-48e5-8af9-5c8ecb3b270a.png)

The functionality should be as on click next  or another page of selected filter category, it should give the next page of same filter's category.

**Comment by itx-stefanie-doell** [comment]
Thank you for opening this issue and describing it which so much information. We will have a look at it in the next days.
