### ISSUE TITLE
Clean up old applications

### ISSUE THREAD

**Issue by the-andyman** [itx-informationssysteme/jobapplications#93]
The users manual says _"There are two tasks implemented to manage applications that are not needed anymore or have to be removed for privacy law reasons."_
How can I set up this "Task"?
Neither in the extension, nor in the "TYPO3 Scheduler" I find a suitable entry.

**Comment by julienco03** [comment]
Hey there, thanks for reaching out!

To use the "tasks" you first have to select _Execute console commands_ as Class.

![image](https://github.com/itx-informationssysteme/jobapplications/assets/85078802/80d3e6f6-5314-45e0-864e-bfee6c6ef6e4)

Then you'll find the option _Schedulable Command. Save and reopen to define command arguments_ below. Now you can choose between following commands:
1. jobapplications:anonymizeApplicationsCommand: This command anonymizes applications and deletes the application's files.
2. jobapplications:cleanupApplicationsCommand: This command deletes applications and deletes the application's files.

Also, don't forget to set a frequency.

![image](https://github.com/itx-informationssysteme/jobapplications/assets/85078802/d1fd68be-7f87-4650-8302-13ab6905cbbe)

After saving, you'll find two new options to configurate the command:

![image](https://github.com/itx-informationssysteme/jobapplications/assets/85078802/fb672b41-1ef0-4e0d-a5d2-6668f2202993)
