### ISSUE TITLE
Structured data for Google Jobs

### ISSUE THREAD

**Issue by der-phillip** [itx-informationssysteme/jobapplications#98]
Hello, in the features it says there is [Structured data for Google Jobs](https://github.com/itx-informationssysteme/jobapplications/blob/develop/Documentation/Introduction/Index.rst#manage-job-postings) integration

I could not find any [markup](https://developers.google.com/search/docs/appearance/structured-data/job-posting) for it. How is this integrated?

**Comment by itx-benjamin-jasper** [comment]
You can enable this via TypoScript: https://docs.typo3.org/p/itx/jobapplications/2.1/en-us/User/Index.html#enable-google-jobs
